[tox]
envlist = py3{9,10,11,12,13,14,15},pypy3{9,10,11},lint,format,mypy
skip_missing_interpreters=true

[testenv]
extras = test
commands = pytest {posargs}

[testenv:lint]
skip_install = true
deps = ruff
commands = ruff check

[testenv:format]
skip_install = true
deps = ruff
commands = ruff format --check

[testenv:mypy]
basepython = python3.9
extras =
  test
  mypy
commands = mypy .
